export enum TrackStatus {
  UPLOADING = 'UPLOADING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum AudioAssetStatus {
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum ProcessingStage {
  UPLOAD_SOURCE = 'UPLOAD_SOURCE',
  PROBE_SOURCE = 'PROBE_SOURCE',
  ENCODE_64 = 'ENCODE_64',
  ENCODE_128 = 'ENCODE_128',
  ENCODE_256 = 'ENCODE_256',
  ENCODE_320 = 'ENCODE_320',
  VALIDATE_OUTPUT = 'VALIDATE_OUTPUT',
  UPLOAD_OUTPUT = 'UPLOAD_OUTPUT',
  DATABASE = 'DATABASE',
}
