export enum TrackStatus {
  UPLOADING = 'UPLOADING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum AudioAssetStatus {
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum ProcessingStage {
  CREATE_UPLOAD_SESSION = 'CREATE_UPLOAD_SESSION',
  VERIFY_SOURCE_UPLOAD = 'VERIFY_SOURCE_UPLOAD',
  DOWNLOAD_SOURCE = 'DOWNLOAD_SOURCE',
  UPLOAD_SOURCE = 'UPLOAD_SOURCE',
  FETCH_YOUTUBE_METADATA = 'FETCH_YOUTUBE_METADATA',
  DOWNLOAD_YOUTUBE_AUDIO = 'DOWNLOAD_YOUTUBE_AUDIO',
  TRANSCODE_SOURCE = 'TRANSCODE_SOURCE',
  PROBE_SOURCE = 'PROBE_SOURCE',
  ENCODE_64 = 'ENCODE_64',
  ENCODE_128 = 'ENCODE_128',
  ENCODE_256 = 'ENCODE_256',
  ENCODE_320 = 'ENCODE_320',
  VALIDATE_OUTPUT = 'VALIDATE_OUTPUT',
  UPLOAD_OUTPUT = 'UPLOAD_OUTPUT',
  DATABASE = 'DATABASE',
}
